# Experiment Configuration
experiment:
  dataset_root: "/home/yanyan/mnt_yanyan_hpc_nebula_alpha"
  save_dir: "/HDD1/embodied_ai/open_source_test/diffusion_policy/dp_json_results"
  random_seed: 0
  num_traj: 25
  max_episode_steps: 400
  base_seed: 20241201

# Model Configuration
model:
  model_path: "/HDD1/embodied_ai/checkpoints/RDT-ManiSkill/maniskill-model/diffusion_policy/700.ckpt"
  device: "cuda"
  # Data normalization statistics (from training)
  data_stat:
    state_min: [-0.7463043928146362, -0.0801204964518547, -0.4976441562175751, -2.657780647277832, -0.5742632150650024, 1.8309762477874756, -2.2423808574676514, 0.0, 0.0]
    state_max: [0.7645499110221863, 1.4967026710510254, 0.4650936424732208, -0.3866899907588959, 0.5505855679512024, 3.2900545597076416, 2.5737812519073486, 0.03999999910593033, 0.03999999910593033]
    action_min: [-0.7472005486488342, -0.08631071448326111, -0.4995281398296356, -2.658363103866577, -0.5751323103904724, 1.8290787935256958, -2.245187997817993, -1.0]
    action_max: [0.7654682397842407, 1.4984270334243774, 0.46786263585090637, -0.38181185722351074, 0.5517147779464722, 3.291581630706787, 2.575840711593628, 1.0]
    action_mean: [-0.00885344110429287, 0.5523102879524231, -0.007564723491668701, -2.0108158588409424, 0.004714342765510082, 2.615924596786499, 0.08461848646402359, -0.19301606714725494]
    action_std: [0.2199309915304184, 0.18780815601348877, 0.13044124841690063, 0.30669933557510376, 0.1340624988079071, 0.24968451261520386, 0.9589747190475464, 0.9827960729598999]

# Environment Configuration
environment:
  obs_mode: "rgb"
  control_mode: "pd_joint_pos"
  render_mode: "rgb_array"
  reward_mode: "sparse"
  shader: "default"
  sim_backend: "auto"

# Task Lists
tasks:
  capability:
    - "Control-PlaceSphere-Easy"
    - "Control-PushCube-Easy"
    - "Control-StackCube-Easy"
    - "Control-PlaceSphere-Medium"
    - "Control-PegInsertionSide-Medium"
    - "Control-StackCube-Medium"
    - "Control-PlaceSphere-Hard"
    - "Control-PlugCharger-Hard"
    - "Control-StackCube-Hard"
    - "Perception-PlaceBiggerSphere-Easy"
    - "Perception-PlaceRedSphere-Easy"
    - "Perception-PickSphere-Easy"
    - "Perception-PlaceRedT-Medium"
    - "Perception-PlaceDiffCubes-Medium"
    - "Perception-PlaceWhitePeg-Medium"
    - "Perception-PlaceRedT-Hard"
    - "Perception-PlaceRightCubes-Hard"
    - "Perception-PlacePeg-Hard"
    - "Language-PickCube-Easy"
    - "Language-GrabBlock-Easy"
    - "Language-PlaceCube-Easy"
    - "Language-PickCube-Medium"
    - "Language-GrabBlock-Medium"
    - "Language-PlaceCube-Medium"
    - "Language-ConditionalPick-Hard"
    - "Language-SequentialPlace-Hard"
    - "Language-ReferenceSelect-Hard"
    - "SpatialReasoning-PlaceBetween-Easy"
    - "SpatialReasoning-MoveCube-Easy"
    - "SpatialReasoning-PickCube-Easy"
    - "SpatialReasoning-PickClosest-Medium"
    - "SpatialReasoning-PlaceContainer-Medium"
    - "SpatialReasoning-PickCube-Medium"
    - "SpatialReasoning-BuildBlock-Hard"
    - "SpatialReasoning-KitchenAssembly-Hard"
    - "SpatialReasoning-PickCube-Hard"
    - "Dynamic-PressSwitch-Easy"
    - "Dynamic-ColorSwitchPickCube-Easy"
    - "Dynamic-ShapeSwitchPickCube-Easy"
    - "Dynamic-PlaceRollingSphere-Medium"
    - "Dynamic-PickCubeWithCollision-Medium"
    - "Dynamic-PickCubeWithSliding-Medium"
    - "Dynamic-RollBallWithDistraction-Hard"
    - "Dynamic-PlaceRollingSphere-Hard"
    - "Dynamic-RollBall-Hard"
    - "Robust-PlaceSphere-Easy"
    - "Robust-PushCube-Easy"
    - "Robust-StackCube-Easy"
    - "Robust-PlaceSphere-Medium"
    - "Robust-PushCube-Medium"
    - "Robust-StackCube-Medium"
    - "Robust-AssemblingKits-Hard"
    - "Robust-KitchenAssembly-Hard"
    - "Robust-LiftPegUpright-Hard"
  stress:
    - "AdaptationTest-MovingCube"
    - "AdaptationTest-InstructionChange"
    - "AdaptationTest-PickAndPlace"

# Video Configuration
video:
  save_video: true
  save_dir: "/HDD1/embodied_ai/open_source_test/diffusion_policy/simulation_videos"

# Figure Configuration
figure:
  model_name: "Diffusion Policy"
  save_capability_figure: true
  save_stress_figure: true
  save_dir: "/HDD1/embodied_ai/open_source_test/diffusion_policy/figures"