# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/mp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/mp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprotos/mp.proto\x12\x02mp\"\xcf\x01\n\rPlannerConfig\x12\x0c\n\x04urdf\x18\x01 \x01(\t\x12\x0c\n\x04srdf\x18\x02 \x01(\t\x12\x17\n\x0fuser_link_names\x18\x03 \x03(\t\x12\x18\n\x10user_joint_names\x18\x04 \x03(\t\x12\x12\n\nmove_group\x18\x05 \x01(\t\x12\x18\n\x10joint_vel_limits\x18\x06 \x03(\x01\x12\x18\n\x10joint_acc_limits\x18\x07 \x03(\x01\x12\x14\n\x0c\x62\x61se_pose_pq\x18\x08 \x03(\x01\x12\x11\n\ttime_step\x18\t \x01(\x01\"u\n\x11PlanToPoseRequest\x12\x1e\n\x03\x63\x66g\x18\x01 \x01(\x0b\x32\x11.mp.PlannerConfig\x12\x11\n\ttarget_pq\x18\x02 \x03(\x01\x12\x14\n\x0c\x63urrent_qpos\x18\x03 \x03(\x01\x12\x17\n\x0fuse_point_cloud\x18\x04 \x01(\x08\"M\n\nTrajectory\x12\x10\n\x08position\x18\x01 \x03(\x01\x12\x10\n\x08velocity\x18\x02 \x03(\x01\x12\x0b\n\x03\x64of\x18\x03 \x01(\x05\x12\x0e\n\x06n_step\x18\x04 \x01(\x05\"9\n\tPlanReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1c\n\x04traj\x18\x02 \x01(\x0b\x32\x0e.mp.Trajectory\",\n\x0fUpdatePCRequest\x12\x0e\n\x06points\x18\x01 \x03(\x02\x12\t\n\x01n\x18\x02 \x01(\x05\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xd9\x01\n\x07Planner\x12\x32\n\nPlanToPose\x12\x15.mp.PlanToPoseRequest\x1a\r.mp.PlanReply\x12\x31\n\tPlanScrew\x12\x15.mp.PlanToPoseRequest\x1a\r.mp.PlanReply\x12\x38\n\x10UpdatePointCloud\x12\x13.mp.UpdatePCRequest\x1a\x0f.mp.StatusReply\x12-\n\x0f\x43learCollisions\x12\t.mp.Empty\x1a\x0f.mp.StatusReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.mp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANNERCONFIG']._serialized_start=24
  _globals['_PLANNERCONFIG']._serialized_end=231
  _globals['_PLANTOPOSEREQUEST']._serialized_start=233
  _globals['_PLANTOPOSEREQUEST']._serialized_end=350
  _globals['_TRAJECTORY']._serialized_start=352
  _globals['_TRAJECTORY']._serialized_end=429
  _globals['_PLANREPLY']._serialized_start=431
  _globals['_PLANREPLY']._serialized_end=488
  _globals['_UPDATEPCREQUEST']._serialized_start=490
  _globals['_UPDATEPCREQUEST']._serialized_end=534
  _globals['_STATUSREPLY']._serialized_start=536
  _globals['_STATUSREPLY']._serialized_end=565
  _globals['_EMPTY']._serialized_start=567
  _globals['_EMPTY']._serialized_end=574
  _globals['_PLANNER']._serialized_start=577
  _globals['_PLANNER']._serialized_end=794
# @@protoc_insertion_point(module_scope)
