# Experiment Configuration
experiment:
  dataset_root: "" # path to the dataset root
  save_dir: "" # path to save experiment results
  num_traj: 25
  max_episode_steps: 400
  random_seed: 0 
  base_seed: 20241201
  # [more experiment options can be added here]

# Model Configuration
model:
  model_path: "" # path to model checkpoint
  # [more model options can be added here]

# Environment Configuration
environment:
  obs_mode: "rgb"
  control_mode: "pd_joint_pos"
  render_mode: "rgb_array"
  reward_mode: "sparse"
  shader: "default"
  sim_backend: "auto"

# Task Lists
tasks:
  capability:
    - "Control-PlaceSphere-Easy"
    - "Control-PushCube-Easy"
    - "Control-StackCube-Easy"
    - "Control-PlaceSphere-Medium"
    - "Control-PegInsertionSide-Medium"
    - "Control-StackCube-Medium"
    - "Control-PlaceSphere-Hard"
    - "Control-PlugCharger-Hard"
    - "Control-StackCube-Hard"
    - "Perception-PickBiggerSphere-Easy"
    - "Perception-PickRedSphere-Easy"
    - "Perception-PickSphere-Easy"
    - "Perception-PlaceRedT-Medium"
    - "Perception-PlaceDiffCubes-Medium"
    - "Perception-PlaceWhitePeg-Medium"
    - "Perception-PlaceRedT-Hard"
    - "Perception-PlaceRightCubes-Hard"
    - "Perception-PlacePeg-Hard"
    - "Language-PickCube-Easy"
    - "Language-GrabBlock-Easy"
    - "Language-PlaceCube-Easy"
    - "Language-PickCube-Medium"
    - "Language-GrabBlock-Medium"
    - "Language-PlaceCube-Medium"
    - "Language-ConditionalPick-Hard"
    - "Language-SequentialPlace-Hard"
    - "Language-ReferenceSelect-Hard"
    - "SpatialReasoning-PlaceBetween-Easy"
    - "SpatialReasoning-MoveCube-Easy"
    - "SpatialReasoning-PickCube-Easy"
    - "SpatialReasoning-PickClosest-Medium"
    - "SpatialReasoning-PlaceContainer-Medium"
    - "SpatialReasoning-PickCube-Medium"
    - "SpatialReasoning-BuildBlock-Hard"
    - "SpatialReasoning-KitchenAssembly-Hard"
    - "SpatialReasoning-PickCube-Hard"
    - "Dynamic-PressSwitch-Easy"
    - "Dynamic-ColorSwitchPickCube-Easy"
    - "Dynamic-ShapeSwitchPickCube-Easy"
    - "Dynamic-PlaceRollingSphere-Medium"
    - "Dynamic-PickCubeWithCollision-Medium"
    - "Dynamic-PickCubeWithSliding-Medium"
    - "Dynamic-RollBallWithDistraction-Hard"
    - "Dynamic-PlaceRollingSphere-Hard"
    - "Dynamic-RollBall-Hard"
    - "Robust-PlaceSphere-Easy"
    - "Robust-PushCube-Easy"
    - "Robust-StackCube-Easy"
    - "Robust-PlaceSphere-Medium"
    - "Robust-PushCube-Medium"
    - "Robust-StackCube-Medium"
    - "Robust-AssemblingKits-Hard"
    - "Robust-KitchenAssembly-Hard"
    - "Robust-LiftPegUpright-Hard"

  stress:
    - "AdaptationTest-MovingCube"
    - "AdaptationTest-InstructionChange"
    - "AdaptationTest-PickAndPlace"

video:
  save_video: true
  save_dir: "" # path to save videos

figure:
  model_name: model # model name for figure title
  save_capability_figure: true
  save_stress_figure: true
  save_dir: "" # path to save figures